---
qb_schema:
  custom_class_Appointment:
    name: Appointment
    fields:
      provider_id: Integer
      client_id: Integer
      dialog_id: String
      description: String
      priority: Integer
      notes: String
      conclusion: String
      language: String
      date_end: Date
    permissions:
      read:
        access: open
        primary: true
      update:
        access: open
        primary: true
      delete:
        access: open
      create:
        access: open
        primary: true
  custom_class_Record:
    name: Record
    fields:
      name: String
      appointment_id: String
      transcription: String_a
      summary: String
      actions: String
      uid: String
    permissions:
      read:
        access: open
      update:
        access: owner
      delete:
        access: owner
      create:
        access: open
        primary: true
